name: windows-exe-integration-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create and activate venv
        shell: powershell
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1
          Write-Host "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
          # Build from repository root where launch_viewer_webview.py and viewer/ live
          Set-Location $env:GITHUB_WORKSPACE
          Write-Host "PWD = $(Get-Location)"
          Write-Host "Listing files in working dir:"
          Get-ChildItem -Force | Select-Object Name,Length | Format-Table -AutoSize
          # Clean previous artifacts
          Remove-Item -Recurse -Force .\build, .\dist, .\*.spec -ErrorAction SilentlyContinue
          # Build
          pyinstaller --clean --onefile --console --add-data "viewer;viewer" launch_viewer_webview.py
          # Verify artifact
          if (-not (Test-Path "dist\launch_viewer_webview.exe")) {
            Write-Error "PyInstaller build failed: EXE not found at dist\launch_viewer_webview.exe"
            exit 1
          }
          Write-Host "Build succeeded, EXE size:" (Get-Item "dist\launch_viewer_webview.exe").Length "bytes"

      - name: Run integration test against EXE
        shell: powershell
        env:
          PYTHONUTF8: 1
        run: |
          .\.venv\Scripts\Activate.ps1
          # Run integration test and capture log
          python .\integration_test.py --exe ".\dist\launch_viewer_webview.exe" --port 60031 --no-new-console *> integration_test_with_exe_log.txt
          Write-Host "=== Integration Test Log (tail 200) ==="
          Get-Content .\integration_test_with_exe_log.txt -Tail 200

      - name: Upload integration test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration_test_artifacts
          path: integration_test_artifacts/

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            dist/launch_viewer_webview.exe
            build/
            *.spec
