name: Windows smoke tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-windows:
    runs-on: windows-latest
    env:
      PYTHONUNBUFFERED: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell execution policy
        shell: pwsh
        run: Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Check for existing FFmpeg
        id: ffcheck
        shell: pwsh
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            Write-Host "ffmpeg found"
            "ffmpeg_exists=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding ascii
          } else {
            "ffmpeg_exists=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding ascii
          }

      - name: Install Chocolatey (robust method)
        shell: pwsh
        run: |
          try {
            if (Get-Command choco -ErrorAction SilentlyContinue) {
              Write-Host "Chocolatey already installed"
              exit 0
            }
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            $chocoBin = "$env:ALLUSERSPROFILE\chocolatey\bin"
            Add-Content -Path $env:GITHUB_PATH -Value $chocoBin
            $env:Path = "$chocoBin;$env:Path"
            if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
              throw "Chocolatey installation failed"
            }
            Write-Host "Chocolatey installed successfully"
          }
          catch {
            Write-Error "Chocolatey installation failed: $($_.Exception.Message)"
            exit 1
          }

      - name: Install FFmpeg via Chocolatey
        if: env.ffmpeg_exists == 'false'
        shell: pwsh
        run: |
          $maxRetries = 4
          $chocoBin = "$env:ALLUSERSPROFILE\chocolatey\bin"
          for ($i = 1; $i -le $maxRetries; $i++) {
            try {
              choco install ffmpeg -y --no-progress
              if (-not ($env:Path -split ';' | Where-Object { $_ -eq $chocoBin })) {
                Add-Content -Path $env:GITHUB_PATH -Value $chocoBin
                $env:Path = "$chocoBin;$env:Path"
              }
              if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
                Write-Host "FFmpeg installed successfully"
                break
              }
              throw "ffmpeg not found after install"
            }
            catch {
              Write-Host "Attempt $i failed: $($_.Exception.Message)"
              if ($i -eq $maxRetries) { exit 1 }
              Start-Sleep -Seconds (5 * $i)
            }
          }

      - name: Download and extract FFmpeg (no Chocolatey)
        if: env.ffmpeg_exists == 'false'
        shell: pwsh
        run: |
          $url     = 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip'
          $dst     = Join-Path $env:RUNNER_TEMP 'ffmpeg.zip'
          $extract = Join-Path $env:RUNNER_TEMP 'ffmpeg'
          Invoke-WebRequest -Uri $url -OutFile $dst
          if (-Not (Test-Path $extract)) { New-Item -ItemType Directory -Path $extract | Out-Null }
          Expand-Archive -LiteralPath $dst -DestinationPath $extract -Force
          $ff  = Get-ChildItem $extract -Directory | Select-Object -First 1
          $bin = Join-Path $ff.FullName 'bin'
          Write-Host "Adding $bin to PATH for this job"
          Add-Content -Path $env:GITHUB_PATH -Value $bin

      - name: Verify FFmpeg available
        if: env.ffmpeg_exists == 'false'
        shell: pwsh
        run: |
          if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
            Write-Error "ffmpeg not found in PATH"
            exit 1
          }
          ffmpeg -version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify core dependencies
        shell: pwsh
        run: |
          if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
            Write-Error "Python not found"
            exit 1
          }
          python --version
          if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
            Write-Error "FFmpeg not found"
            exit 1
          }
          ffmpeg -version

      - name: Install Python dependencies
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            Write-Host "Found requirements.txt, sanitizing..."
            $tempReq = Join-Path $env:RUNNER_TEMP "requirements.cleaned.txt"
            $lines = Get-Content requirements.txt |
              Where-Object { $_ -and $_ -notmatch '^\s*(ECHO is off\.|@?ECHO\s+OFF\b|rem\b|\#)' } |
              ForEach-Object { $_.Trim() } |
              Where-Object { $_ -ne '' }
            if ($lines.Count -gt 0) {
              $lines | Set-Content -Path $tempReq -Encoding UTF8
              Write-Host "Installing Python packages from requirements"
              python -m pip install --upgrade pip
              python -m pip install -r $tempReq
            } else {
              Write-Host "No valid requirements found; skipping pip install"
            }
          } else {
            Write-Host "No requirements.txt; skipping pip install"
          }

      - name: Start background HTTP server
        shell: pwsh
        run: |
          $proc = Start-Process -NoNewWindow -FilePath python -ArgumentList "-m","http.server","8000" -PassThru
          $proc.Id | Out-File (Join-Path $env:RUNNER_TEMP "server_pid.txt") -Encoding ascii
          Start-Sleep -Seconds 3

      - name: Run smoke tests
        shell: pwsh
        run: |
          Write-Host "Running smoke tests"
          python -c "print('Python execution test passed')"
          try {
            Invoke-WebRequest http://localhost:8000 -UseBasicParsing -TimeoutSec 5 | Out-Null
            Write-Host "HTTP server connectivity test passed"
          } catch {
            Write-Warning "HTTP server test failed"
          }
          try {
            ffmpeg -hide_banner -loglevel error -f lavfi -i testsrc2=duration=1:size=320x240:rate=1 -f null - | Out-Null
            Write-Host "FFmpeg functionality test passed"
          } catch {
            Write-Warning "FFmpeg test failed"
          }

      - name: Cleanup background processes
        if: always()
        shell: pwsh
        run: |
          $pidFile = Join-Path $env:RUNNER_TEMP "server_pid.txt"
          if (Test-Path $pidFile) {
            Stop-Process -Id (Get-Content $pidFile) -ErrorAction SilentlyContinue
          }
          Get-Process python -ErrorAction SilentlyContinue |
            Where-Object { $_.CommandLine -match "http.server" } |
            Stop-Process -Force

      - name: Ensure ci requirements artifact exists
        if: always()
        shell: pwsh
        run: |
          $ciDir = Join-Path $PWD "ci"
          if (-not (Test-Path $ciDir)) { New-Item -ItemType Directory -Path $ciDir -Force | Out-Null }
          $ciReq = Join-Path $ciDir "requirements.ci.txt"
          if (-not (Test-Path $ciReq)) {
            Write-Host "Generating placeholder $ciReq"
            "numpy==1.26.0" | Out-File -FilePath $ciReq -Encoding UTF8
          } else {
            Write-Host "$ciReq already exists; leaving unchanged"
          }

      - name: Upload test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-outputs
          path: |
            outputs/
            *.log
            ci/requirements.ci.txt
            ${{ runner.temp }}/requirements.cleaned.txt
          retention-days: 7
