name: windows-exe-integration-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create and activate venv and install PyInstaller
        shell: powershell
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller (diagnose)
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1

          Write-Host "PWD = $((Get-Location).Path)"
          Write-Host "Files at root:"
          Get-ChildItem -Name

          # Ensure files exist at root
          if (-not (Test-Path "launch_viewer_webview.py")) {
            Write-Error "launch_viewer_webview.py not found at repo root"
            exit 1
          }
          if (-not (Test-Path "viewer")) {
            Write-Error "viewer/ directory not found at repo root"
            exit 1
          }

          # Clean old builds
          Remove-Item -Recurse -Force build, dist, *.spec -ErrorAction SilentlyContinue

          # Build EXE
          pyinstaller --clean --log-level=DEBUG --onefile --console `
            --add-data "viewer;viewer" `
            --distpath dist --workpath build --specpath build `
            launch_viewer_webview.py

          # Show warnings
          $warn = Get-ChildItem build -Filter "warn-*.txt" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($warn) {
            Write-Host "=== PyInstaller warn file ==="
            Get-Content $warn.FullName -Tail 200
          }

          # Verify EXE
          if (-not (Test-Path "dist\launch_viewer_webview.exe")) {
            Write-Error "Build failed: dist\launch_viewer_webview.exe not found"
            exit 1
          }
          $exe = Get-Item "dist\launch_viewer_webview.exe"
          Write-Host "✅ Build succeeded: $($exe.Length) bytes"

      - name: Run integration test against EXE
        shell: powershell
        env:
          PYTHONUTF8: 1
        run: |
          .\.venv\Scripts\Activate.ps1
          New-Item -ItemType Directory -Path integration_test_artifacts -Force | Out-Null

          python .\integration_test.py `
            --exe "dist\launch_viewer_webview.exe" `
            --port 60031 --no-new-console *> integration_test_with_exe_log.txt

          Write-Host "=== Integration Test Log (tail 200) ==="
          Get-Content .\integration_test_with_exe_log.txt -Tail 200

      - name: Collect integration test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration_test_artifacts
          path: integration_test_artifacts/

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            dist/launch_viewer_webview.exe
            build/
            *.spec
