name: Windows smoke tests

on:
  push:
    branches:
      - main
      - 'smoke-*'
  workflow_dispatch: {}

jobs:
  smoke-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check python on runner
        shell: pwsh
        run: |
          Write-Host "=== PATH ==="
          Write-Host $env:PATH
          Write-Host "=== Get-Command python ==="
          Get-Command python -ErrorAction SilentlyContinue | Format-List *
          Write-Host "=== where.exe python ==="
          where.exe python || Write-Host "where.exe returned no python"
          Write-Host "=== python --version ==="
          python --version || Write-Host "python not found"

      - name: Install Python deps
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found, skipping pip install"
          }

      - name: Start static server in background (Start-Process)
        shell: pwsh
        run: |
          Write-Host "Starting http.server with Start-Process (python on PATH)"
          Get-Command python
          Start-Process -NoNewWindow -FilePath python -ArgumentList "-m","http.server","8000"
          Start-Sleep -Seconds 2
          # verify server started (list processes)
          Get-Process python -ErrorAction SilentlyContinue || Write-Host "python process not found"

      - name: Alternative: Start static server as background job (if Start-Process fails)
        if: failure() # runs only if previous step failed
        shell: pwsh
        run: |
          Write-Host "Starting http.server as Start-Job fallback"
          $job = Start-Job -ScriptBlock { python -m http.server 8000 }
          Start-Sleep -Seconds 2
          Get-Job

      - name: Run smoke tests
        shell: pwsh
        run: |
          Write-Host "Run your smoke test command here"
          # adjust working-directory or command as needed
          # Example:
          # pushd src
          # python trace_runner.py --smoke
          # popd
          # Replace the following with your actual smoke test command:
          python -c "print('replace with your smoke test command')"

      - name: Upload outputs (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs

