name: windows-exe-integration-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create and activate venv and install PyInstaller
        shell: powershell
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller (diagnose)
        shell: powershell
        run: |
          .\.venv\Scripts\Activate.ps1

          Write-Host "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
          Write-Host "Python version: $(python --version)"
          Write-Host "PyInstaller version: $(pyinstaller --version)"

          # Ensure we are at repo root (adjust if your sources are elsewhere)
          Set-Location $env:GITHUB_WORKSPACE
          Write-Host "PWD = $(Get-Location)"
          Write-Host "Top-level files and directories:"
          Get-ChildItem -Force | Select-Object Name,Length | Format-Table -AutoSize

          # Install project requirements if present (helps PyInstaller import-time)
          if (Test-Path requirements.txt) {
            Write-Host "Installing requirements.txt"
            pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found, skipping dependency install"
          }

          # Verify correct entrypoint and static assets exist at repo root
          if (-not (Test-Path ".\launch_viewer_webview.py")) {
            Write-Error "Required entrypoint launch_viewer_webview.py not found in repo root. Update workflow to point to your actual launcher script."
            exit 1
          }
          if (-not (Test-Path ".\viewer")) {
            Write-Host "Warning: viewer/ directory not found in repo root. If static assets are required, ensure viewer/ is committed."
          }

          # Clean prior build output
          Remove-Item -Recurse -Force .\build, .\dist, .\*.spec -ErrorAction SilentlyContinue

          # Run PyInstaller; Windows add-data uses semicolon separator
          pyinstaller --clean --log-level=DEBUG --onefile --console --add-data "viewer;viewer" --distpath dist --workpath build --specpath build launch_viewer_webview.py

          # Dump PyInstaller warn file for diagnostics if present
          Get-ChildItem -Path build -Filter "warn-*.txt" -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
            Write-Host "=== PyInstaller warn file: $($_.FullName) ==="
            Get-Content $_.FullName -Tail 400
          }

          # Fail loudly if EXE not produced
          if (-not (Test-Path "dist\launch_viewer_webview.exe")) {
            Write-Error "PyInstaller build failed: dist\launch_viewer_webview.exe not found"
            exit 1
          }
          Write-Host "✅ Build succeeded, EXE size:" (Get-Item "dist\launch_viewer_webview.exe").Length "bytes"

      - name: Run integration test against EXE
        shell: powershell
        env:
          PYTHONUTF8: 1
        run: |
          .\.venv\Scripts\Activate.ps1
          New-Item -ItemType Directory -Path integration_test_artifacts -Force | Out-Null

          python .\integration_test.py --exe ".\dist\launch_viewer_webview.exe" --port 60031 --no-new-console *> integration_test_with_exe_log.txt

          Write-Host "=== Integration Test Log (tail 200) ==="
          Get-Content .\integration_test_with_exe_log.txt -Tail 200

      - name: Upload integration test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration_test_artifacts
          path: integration_test_artifacts/

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            dist/launch_viewer_webview.exe
            build/
            *.spec
