name: Windows smoke tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-windows:
    runs-on: windows-latest
    env:
      PYTHONUNBUFFERED: '1'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Best Practice: Use a dedicated action for FFmpeg ---
      - name: Setup FFmpeg (Reliable Method)
        # Replaces complex Chocolatey logic with a robust, platform-aware action
        uses: wassimk/setup-ffmpeg@v1
        with:
          # You can specify a version if needed, otherwise it uses the latest stable version.
          # version: '6.1'

      - name: Verify FFmpeg Installation
        shell: pwsh
        run: |
          Write-Host "FFmpeg successfully installed and available via setup-ffmpeg action."
          ffmpeg -version # This is now guaranteed to work if the action succeeded.

      - name: Setup Python 3.11 and Cache Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      # --- Python Setup and Dependencies ---

      - name: Install Python Dependencies
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found; skipping pip install."
          }

      - name: Create Output Directory
        shell: pwsh
        run: New-Item -Path 'outputs' -ItemType Directory -Force

      # --- Execution Steps ---

      - name: Start static server in background
        id: start_server
        shell: pwsh
        run: |
          # Save the process ID to a file for explicit cleanup later
          $pidFile = "server_pid.txt"
          Write-Host "Starting http.server in background on port 8000"
          $process = Start-Process -NoNewWindow -PassThru -FilePath python -ArgumentList "-m","http.server","8000"
          $process.Id | Out-File -FilePath $pidFile -Encoding UTF8
          Start-Sleep -Seconds 2

      - name: Run smoke command
        shell: pwsh
        run: |
          python -c "print('smoke test placeholder running...')"

      - name: Optional ffmpeg task
        shell: pwsh
        run: |
          # Now we can reliably use FFmpeg without an 'if' guard.
          ffmpeg -hide_banner -loglevel error -version

      # --- Cleanup and Artifact Upload ---
      
      - name: Stop Background Server (Crucial Cleanup)
        if: always()
        shell: pwsh
        run: |
          $pidFile = "server_pid.txt"
          if (Test-Path $pidFile) {
            $pid = Get-Content $pidFile -ErrorAction SilentlyContinue
            if ($pid -and $pid -as [int]) {
              Write-Host "Stopping server with PID: $pid"
              Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
            }
          }
      
      - name: Upload outputs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs
