name: Windows smoke tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke-windows:
    # Use a more specific job name if needed, but smoke-windows is fine.
    runs-on: windows-latest
    env:
      # Ensures Python output appears immediately in the logs
      PYTHONUNBUFFERED: '1'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Dependency Installation (Simplified and Robust) ---
      
      - name: Install FFmpeg using Chocolatey
        # Chocolatey is pre-installed on windows-latest, we just need to use it.
        # Its bin directory is already in the environment path on the runner.
        shell: pwsh
        run: |
          Write-Host "Installing ffmpeg via choco..."
          # Install ffmpeg. We rely on the runner environment to handle retries/path setup.
          choco install ffmpeg -y --no-progress
          
      - name: Verify FFmpeg Installation
        shell: pwsh
        run: |
          if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) { 
            Write-Error "ffmpeg not available on PATH"; exit 1 
          }
          ffmpeg -version

      - name: Setup Python 3.11 and Cache Dependencies
        # Use actions/setup-python@v5 (recommended) and add caching for speed.
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt # Caches based on the contents of this file

      # --- Python Setup and Dependencies ---

      - name: Install Python Dependencies
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            # Upgrade pip first (good practice) and install dependencies
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          } else {
            Write-Host "No requirements.txt found; skipping pip install."
          }

      - name: Create Output Directory
        shell: pwsh
        run: New-Item -Path 'outputs' -ItemType Directory -Force # Ensure the directory exists for artifact upload

      # --- Execution Steps ---

      - name: Start static server in background
        # Save the process ID to a file for explicit cleanup later
        id: start_server
        shell: pwsh
        run: |
          $pidFile = "server_pid.txt"
          Write-Host "Starting http.server in background on port 8000"
          # Start-Process with -PassThru returns the process object
          $process = Start-Process -NoNewWindow -PassThru -FilePath python -ArgumentList "-m","http.server","8000"
          # Write the PID to the file
          $process.Id | Out-File -FilePath $pidFile -Encoding UTF8
          Start-Sleep -Seconds 2

      - name: Run smoke command
        shell: pwsh
        run: |
          # Replace this placeholder with your actual smoke test command
          python -c "print('smoke test placeholder running...')"

      - name: Optional ffmpeg task
        shell: pwsh
        run: |
          if (Get-Command ffmpeg -ErrorAction SilentlyContinue) {
            ffmpeg -hide_banner -loglevel error -version
          } else {
            Write-Host "ffmpeg not found; skipping ffmpeg task"
          }

      # --- Cleanup and Artifact Upload ---
      
      - name: Stop Background Server (Crucial Cleanup)
        if: always() # Ensure this runs even if the smoke command fails
        shell: pwsh
        run: |
          $pidFile = "server_pid.txt"
          if (Test-Path $pidFile) {
            $pid = Get-Content $pidFile
            Write-Host "Stopping server with PID: $pid"
            # Use Stop-Process to terminate the server by its PID
            Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
          }
      
      - name: Upload outputs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs
